# Import NumPy module

In [1]:
# Once NumPy is installed on your distribution, to import the NumPy module within your Python session
import numpy as np

# ndarray object

In [2]:
a = [1,2,3]
type(a)

list

In [3]:
a = np.array([1, 2, 3])
type(a)

numpy.ndarray

In [4]:
a

array([1, 2, 3])

# ndarray characteristics

In [5]:
a.dtype

dtype('int64')

In [6]:
a.ndim

1

In [7]:
a.shape

(3,)

In [8]:
a.size

3

In [11]:
b = np.array(
    [
    [1.3, 2.4, 2.1],
    [0.3, 4.1, 9.8]
    ])
print('type = ', b.dtype)
print('number of dimensions = ', b.ndim)
print('shape = ', b.shape)
print('size = ', b.size)

type =  float64
number of dimensions =  2
shape =  (2, 3)
size =  6


In [10]:
b

array([[1.3, 2.4, 2.1],
       [0.3, 4.1, 9.8]])

In [12]:
print(b.itemsize) #It defines the size in bytes of each item in the array
print(b.data)

8


In [13]:
len(a) # length

3

In [14]:
a1D = np.array([1, 2, 3, 4])
a1D.shape

(4,)

In [15]:
a2D = np.array(
    [
        [1, 2], 
        [3, 4]
    ])
a2D.shape

(2, 2)

In [18]:
a3D = np.array(
    [
        [
            [1, 2],
            [3, 4]
        ],
        [
            [5, 6], 
            [7, 8]
        ]
    ])
a3D
a3D.shape

(2, 2, 2)

# Types of Data

In [19]:
# For example, data type >> string
g = np.array([['a', 'b'],['c', 'd']])
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [23]:
print(g.dtype)
print(g.dtype.name)

object
object


In [24]:
# if you want to define an array with complex values, you can use the dtype option as follows:
f = np.array([[1, 2, 3],[4, 5, 6]], dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [25]:
n = np.array([['1', '2'],['3', '4']])
n.astype(int) # Convert an array to a different type

array([[1, 2],
       [3, 4]])

# Create an Array

## First: Converting Python sequences to NumPy Arrays

In [26]:
# pass a list to the array() function
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [27]:
# pass a sequence of lists to the array() function
b = np.array([[1, 2, 3],[4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# tuples
c = np.array((1, 2, 3))
c

array([1, 2, 3])

In [29]:
# sequences of tuples.
d = np.array(((1, 2, 3),(4, 5, 6)))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# sequences of tuples and interconnected lists 
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Second: Intrinsic Creation of an Array

In [31]:
# The NumPy library provides a set of functions that generate ndarrays with initial content
# The zeros() function, for example, creates a full array of zeros with dimensions defined by the shape argument. 
# For example, to create a two-dimensional array 3x3, you can use:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
# ones() function creates an array full of ones in a very similar way.
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
# arange(start, end) is a function generates NumPy arrays with numerical sequences 
np.arange(0, 10) # generate a sequence of values between 0 and 10 (end value not include)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [38]:
# generate a sequence of values with precise intervals between them. 
# arange(start, end, gap)
# the gap between one value and the next one in the sequence of values.
np.arange(0, 12, 3) 

array([0, 3, 6, 9])

In [39]:
# gap can also be a float.
np.arange(0, 6, 0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [40]:
# Another function very similar to arange() is linspace(). 
# arguments (initial value, end value, number of elements)
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Note: (arange vs. linspace)
- **arange** will not include the end value.
- **linspace** will include the end value.

In [44]:
# random() function will generate an array with many elements as specified in the argument.
np.random.random(3) # The numbers obtained will vary with every run. 

array([0.40541394, 0.6766204 , 0.95134586])

In [45]:
# To create a multidimensional array, you simply pass the size of the array as an argument.
np.random.random((3,3))

array([[0.9882514 , 0.30174036, 0.95625589],
       [0.47254607, 0.297183  , 0.10110072],
       [0.93106808, 0.62941477, 0.32749889]])

In [46]:
np.random.rand(3,3) # uniform distribution (0 to 1)

array([[0.87052082, 0.42260527, 0.63379709],
       [0.56719055, 0.07562217, 0.84307535],
       [0.93039608, 0.49603921, 0.64495949]])

In [47]:
np.random.randn(4,4) # standard (normal or Gaussian) distribution (center around 0)

array([[ 1.23408001, -0.73831917,  0.36498857,  2.15344594],
       [-0.05828603,  1.36740617,  2.25124244,  0.80727366],
       [ 0.7734747 , -1.02615719,  1.03638099,  0.79575815],
       [-0.05463031, -0.48142762,  0.93477755,  0.19805032]])

In [48]:
np.random.randint(2, 10) # 2 inclusive but 10 exclusive

9

In [49]:
np.random.randint(2, size=10) # random 10 integers (from 0 to 1)

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1])

In [50]:
np.random.randint(5, size=(2, 4)) # random 2*4 array (from 0 to 4)

array([[1, 3, 1, 1],
       [2, 0, 2, 2]])

In [51]:
np.full((4,4),11) #(shape, fill_value)

array([[11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11]])

In [52]:
np.full((4, 4), [1, 2, 3, 4])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [53]:
np.eye(7) # [identity matrix] Return a 2-D array with ones on the diagonal and zeros elsewhere
# identity matrix is a square matrix (1's on diagonal and other elements are 0's).

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [55]:
np.empty([3, 2], dtype=int) #(shape, dtype), Return a new array of given shape and type, without initializing entries

array([[ 0, 13],
       [ 0,  0],
       [ 0,  0]])

# Shape Manipulation

In [56]:
a = np.arange(0, 12) # one-dimensional arrays
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
# To generate two-dimensional arrays you can use reshape() function. 
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
# another way by modifying shape attribute
a.shape = (3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
# ravel() function is inverse operation >> convert a two-dimensional array into a one-dimensional array
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
# inverting the columns with the rows by transpose()
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# Basic Operations
## 1- Arithmetic Operators

In [62]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [63]:
a+4

array([4, 5, 6, 7])

In [64]:
a*2

array([0, 2, 4, 6])

In [65]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [66]:
a + b # Addition

array([ 4,  6,  8, 10])

In [67]:
np.add(a, b) 

array([ 4,  6,  8, 10])

In [68]:
a - b # Subtraction

array([-4, -4, -4, -4])

In [69]:
np.subtract(a,b)

array([-4, -4, -4, -4])

In [70]:
a * b # Multiplication

array([ 0,  5, 12, 21])

In [71]:
np.multiply(a, b)

array([ 0,  5, 12, 21])

In [72]:
a / b # Division

array([0.        , 0.2       , 0.33333333, 0.42857143])

In [73]:
np.divide(a,b)

array([0.        , 0.2       , 0.33333333, 0.42857143])

## 2-The Matrix Product

In [76]:
A = np.arange(0, 9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [77]:
B = np.ones((3, 3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [78]:
A * B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [79]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [80]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [81]:
np.dot(B,A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

## 3-Increment and Decrement Operators

In [82]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [83]:
a += 1
a

array([1, 2, 3, 4])

In [84]:
a -= 1
a

array([0, 1, 2, 3])

In [85]:
a += 4
a

array([4, 5, 6, 7])

In [86]:
a *= 2
a

array([ 8, 10, 12, 14])

## 4-Universal Functions (ufunc)

In [87]:
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [88]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [89]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [90]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [91]:
np.exp(a) # Exponentiation

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

## 5-Aggregate Functions

In [92]:
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
a.sum()

15.0

In [93]:
a.min()

0.3

In [94]:
a.max()

5.7

In [95]:
a.argmax() # return the index of maximum number

3

In [96]:
a.mean() #(sum of elements/number of elements) 15/5 = 3

3.0

In [97]:
a.std()

2.0079840636817816

# Indexing, Slicing, and Iterating

## First: Indexing

In [98]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [99]:
a[4]

14

In [100]:
print(a[-1])
print(a[-6])

15
10


In [101]:
a[[1, 3, 4]] # two square brackets [[]]

array([11, 13, 14])

In [102]:
A = np.arange(10, 19).reshape((3, 3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [103]:
A[1, 2]

15

In [104]:
A[2, 0]

16

In [105]:
A[2][0]

16

In [109]:
A[0]

16

## Second: Slicing

In [110]:
a = np.arange(10, 16)

In [111]:
a

array([10, 11, 12, 13, 14, 15])

In [112]:
a[1:5] #[start index, final index]

array([11, 12, 13, 14])

In [113]:
# skip a specific number of following items, then extract the next and skip again
# third number defines the gap in the sequence of the elements
a[1:5:2]  #[start index, final index, gap]

array([11, 13])

In [114]:
a[1:5:3]

array([11, 14])

In [115]:
# omitting
a[::2] #[start index =0, final index = maximum index, gap = 2]

array([10, 12, 14])

In [116]:
a[::3] #[start index =0, final index = maximum index, gap = 3]

array([10, 13])

In [117]:
a[:5:2] #[start index =0, final index = 5, gap = 2]

array([10, 12, 14])

In [118]:
a[:5:] #[start index =0, final index = 5, gap = 1]

array([10, 11, 12, 13, 14])

In [119]:
a[:]

array([10, 11, 12, 13, 14, 15])

In [120]:
# two-dimensional array
A = np.arange(10, 19).reshape((3, 3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [121]:
A[0,:] #[row=0 , column=all]

array([10, 11, 12])

In [122]:
A[:,0] #[row=all , column=0]

array([10, 13, 16])

In [123]:
A[0:2, 0:2]

array([[10, 11],
       [13, 14]])

In [124]:
# not contiguous indexes >> specify an array of indexes.
A[[0,2], 0:2]

array([[10, 11],
       [16, 17]])

## Third: Iterating

### loop in python

In [125]:
for i in a:
    print(i)

10
11
12
13
14
15


In [126]:
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [127]:
# loop in python (two-dimensional array)
for row in A:
    for item in row:
        print(item)

10
11
12
13
14
15
16
17
18


In [128]:
for item in A.flat:
    print(item)

10
11
12
13
14
15
16
17
18


### loop in Numpy

In [129]:
# three arguments: the aggregate function, the axis on which to apply the iteration, and the array
# axis = 0(columns), axis = 1(rows)
np.apply_along_axis(np.mean, axis=0, arr=A)

array([13., 14., 15.])

In [130]:
np.apply_along_axis(np.mean, axis=1, arr=A)

array([11., 14., 17.])

In [131]:
def f2(x):
    return x/2

np.apply_along_axis(f2, axis=1, arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

# Conditions and Boolean Arrays

In [132]:
A = np.random.random((4, 4))
A

array([[0.54024999, 0.76069976, 0.7029165 , 0.42550857],
       [0.85185804, 0.47814027, 0.38390489, 0.56463047],
       [0.68155972, 0.90363726, 0.11052313, 0.31100523],
       [0.1137855 , 0.64806537, 0.68325364, 0.68505035]])

In [133]:
# you wanted to select all the values < 0.5
A < 0.5

array([[False, False, False,  True],
       [False,  True,  True, False],
       [False, False,  True,  True],
       [ True, False, False, False]])

In [134]:
A[A < 0.5]

array([0.42550857, 0.47814027, 0.38390489, 0.11052313, 0.31100523,
       0.1137855 ])

# Array Manipulation

## First: Joining Arrays

In [135]:
A = np.ones((3, 3))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [148]:
B = np.zeros((3, 3))
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [149]:
np.vstack((A, B)) # vertical stacking >> array grows in a vertical direction.

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [146]:
np.hstack((A,B)) # horizontal stacking

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [139]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])

In [140]:
# np.column_stack and np.row_stack used with one-dimensional arrays
# which are stacked as columns or rows in order to form a new two-dimensional array.
np.column_stack((a, b, c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [141]:
np.row_stack((a, b, c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Second: Splitting Arrays

In [150]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [151]:
[B,C] = np.hsplit(A, 2) #split the array horizontally >> the width of the array is divided into parts
B # the 4x4 matrix A will be split into two 2x4 matrices.

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [152]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [153]:
[B,C] = np.vsplit(A, 2) #split the array vertically
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [154]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [156]:
# split() function, which allows you to split the array into nonsymmetrical parts.
# arguments(array, indexes, axis=1(columns) and axis=0(rows))
[A1,A2,A3] = np.split(A,[1,3],axis=1)
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [157]:
A2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [158]:
A3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [159]:
[A1,A2,A3] = np.split(A,[1,3],axis=0)
A1

array([[0, 1, 2, 3]])

In [160]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [161]:
A3

array([[12, 13, 14, 15]])

# Copies or Views of Objects

## Views

In [162]:
a = np.array([1, 2, 3, 4])
b = a
b

array([1, 2, 3, 4])

In [163]:
a[2] = 0
print(a)
print(b) 

[1 2 0 4]
[1 2 0 4]


In [164]:
c = a[0:2]
c

array([1, 2])

In [165]:
a[0] = 0
print(a)
print(c)

[0 2 0 4]
[0 2]


## Copies

In [166]:
a = np.array([1, 2, 3, 4])
c = a.copy()
print(a)
print(c)

[1 2 3 4]
[1 2 3 4]


In [167]:
a[0] = 0
print(a)
print(c)

[0 2 3 4]
[1 2 3 4]


## Resources:

- https://numpy.org/doc/stable/user/absolute_beginners.html
- https://numpy.org/doc/stable/reference/arrays.dtypes.html#arrays-dtypes
- http://datacamp-community-prod.s3.amazonaws.com/ba1fe95a-8b70-4d2f-95b0-bc954e9071b0
- https://numpy.org/doc/stable/user/whatisnumpy.html
- https://learning.oreilly.com/library/view/python-data-analytics/9781484239131/
- https://learning.oreilly.com/library/view/python-for-algorithmic/9781492053347/